### PR TITLE
updated whole footer - added icons with your social account handle keeping your theme colour intact.

### PR DESCRIPTION
**Pull request by Madan2468**
updated whole footer - added icons with your social account handle with effects when cursor placed , added copyright pannel and layout keeping your prev colour theme.Attaching the image how it looks now : 

updation on footer - #1 

Screenshot 2024-10-01 at 1 52 55 AM

### CODE REVIEW

**Comment by Madan2468** [comment]
@ajaynegi45 have a look

**Review by ajaynegi33 — APPROVED** [review]
Hi @Madan2468,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!

If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.

Once again, thank you for your contribution! ❤️

**Comment by Madan2468** [comment]
Thank you too , I can try to enhance the header section so i will raise the issue and you can assign me and we can go further like this.

**Comment by ajaynegi33** [comment]
> Thank you too , I can try to enhance the header section so i will raise the issue and you can assign me and we can go further like this.

Go for it.

**Pull request merged**
